### ISSUE TITLE
Move views/flickrapi.php

### ISSUE THREAD

**Issue by ahoiroman** [sGerli/flick#4]
You should consider moving `views/flickrapi.php` to a `Controller` or `Helper`, which is not located in the views-directory.

**Comment by sGerli** [comment]
I've tried moving it to the src folder, and using `include '../src/flickrapi.php'` but for some reason, it isn't reading it. I'm not sure if I'm missing something (PHP wasn't in my development time until now).

**Comment by ahoiroman** [comment]
Do not include files. Use namespaces and autoloading.

Have a look at this: 

- https://spqr.wtf/blog/2017/08/24/building-extensions-for-pagekit-part-4-namespaces
- https://spqr.wtf/blog/2017/08/19/building-extensions-for-pagekit-part-2-first-steps (Part: Add module definition, check out the autoload-part in there)

**Comment by sGerli** [comment]
Solved by https://github.com/sGerli/flick/commit/e69c3484a638515f8a2e25d0c3de7e7943a29a64
